name: format
on:
  workflow_dispatch:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    name: 'format'
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: format
        shell: bash
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          ./gofmt.sh
          commit () {
            git commit -am "auto-format"
            git push
          }
          git status | grep "nothing to commit, working tree clean" || commit
